-- 删除用户及TABLESPACE
-- ALTER TABLESPACE APOLLO_CONFIG_TABLESPACE OFFLINE;
-- DROP USER APOLLO_CONFIG CASCADE;
-- DROP TABLESPACE APOLLO_CONFIG_TABLESPACE INCLUDING CONTENTS AND DATAFILES;
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建TABLESPACE以及对应的dbf文件初始大小
CREATE TABLESPACE APOLLO_CONFIG_TABLESPACE DATAFILE '/opt/oracle/oradata/ORCL/ORCLPDB/APOLLO_CONFIG_TABLESPACE.dbf' SIZE 5G AUTOEXTEND OFF;
CREATE USER APOLLO_CONFIG IDENTIFIED BY 123456 DEFAULT TABLESPACE APOLLO_CONFIG_TABLESPACE;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO APOLLO_CONFIG;
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建应用表
CREATE TABLE APOLLO_CONFIG.APP (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    NAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ORGID VARCHAR2(32) DEFAULT 'default' NOT NULL,
    ORGNAME VARCHAR2(64) DEFAULT 'default' NOT NULL,
    OWNERNAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    OWNEREMAIL VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT APP_PK PRIMARY KEY (ID),
    CONSTRAINT UK_APPID_DELETEDAT UNIQUE (APPID, DELETEDAT)
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
CREATE INDEX IDX_APP_DATACHANGE_LASTTIME ON APOLLO_CONFIG.APP (DATACHANGE_LASTTIME);
CREATE INDEX IDX_APP_NAME ON APOLLO_CONFIG.APP (SUBSTR(NAME, 1, 191));
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_APP_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.APP
  FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE APOLLO_CONFIG.APP IS '应用表';
COMMENT ON COLUMN APOLLO_CONFIG.APP.ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG.APP.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.APP.NAME IS '应用名';
COMMENT ON COLUMN APOLLO_CONFIG.APP.ORGID IS '部门Id';
COMMENT ON COLUMN APOLLO_CONFIG.APP.ORGNAME IS '部门名字';
COMMENT ON COLUMN APOLLO_CONFIG.APP.OWNERNAME IS 'ownerName';
COMMENT ON COLUMN APOLLO_CONFIG.APP.OWNEREMAIL IS 'ownerEmail';
COMMENT ON COLUMN APOLLO_CONFIG.APP.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.APP.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.APP.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.APP.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.APP.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.APP.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建应用namespace定义表
CREATE TABLE APOLLO_CONFIG.APPNAMESPACE (
  ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  NAME VARCHAR2(32) DEFAULT '' NOT NULL,
  APPID VARCHAR2(64) DEFAULT '' NOT NULL,
  FORMAT VARCHAR2(32) DEFAULT 'properties' NOT NULL,
  ISPUBLIC NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISPUBLIC IN (0,1)),
  "COMMENT" VARCHAR2(64) DEFAULT '' NOT NULL,
  ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
  DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
  DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
  DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
  DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.APPNAMESPACE ADD CONSTRAINT PK_APPSPACE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.APPNAMESPACE ADD CONSTRAINT UK_APPID_NAME_DELETEDAT UNIQUE (APPID, NAME, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_APPSPACE_NAME_APPID ON APOLLO_CONFIG.APPNAMESPACE (NAME, APPID);
CREATE INDEX IDX_APPSPACE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.APPNAMESPACE (DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_APPSPACE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.APPNAMESPACE
 FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加列注释
COMMENT ON TABLE APOLLO_CONFIG.APPNAMESPACE IS '应用namespace定义';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.NAME IS 'namespace名字，需要全局唯一';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.APPID IS 'app id';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.FORMAT IS 'namespace的format类型';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.ISPUBLIC IS 'namespace是否为公共';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.APPNAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建日志审计表
CREATE TABLE APOLLO_CONFIG."AUDIT" (
   ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
   ENTITYNAME VARCHAR2(50) DEFAULT 'default' NOT NULL,
   ENTITYID NUMBER(10) NULL,
   OPNAME VARCHAR2(50) DEFAULT 'default' NOT NULL,
   "COMMENT" VARCHAR2(500) NULL,
   ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0, 1)),
   DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
   DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
   DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '' NULL,
   DATACHANGE_LASTTIME TIMESTAMP DEFAULT SYSTIMESTAMP NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IDX_AUDIT_LASTTIME ON APOLLO_CONFIG."AUDIT" (DATACHANGE_LASTTIME);
-- 创建更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_AUDIT_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG."AUDIT"
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := SYSTIMESTAMP;
END;
/
-- 添加表注释
COMMENT ON TABLE APOLLO_CONFIG."AUDIT" IS '日志审计表';
-- 添加列注释
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".ENTITYNAME IS '表名';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".ENTITYID IS '记录ID';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".OPNAME IS '操作类型';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT"."COMMENT" IS '备注';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG."AUDIT".DATACHANGE_LASTTIME IS '最后修改时间';

------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建集群表
CREATE TABLE APOLLO_CONFIG."CLUSTER" (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR2(32) DEFAULT '' NOT NULL,
    APPID VARCHAR2(64) DEFAULT '' NOT NULL,
    PARENTCLUSTERID NUMBER(10) DEFAULT 0 NOT NULL,
    "COMMENT" VARCHAR2(64),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG."CLUSTER" ADD CONSTRAINT PK_APP_CLUSTER PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG."CLUSTER" ADD CONSTRAINT UK_APPID_NAME_DEL_AT UNIQUE (APPID, NAME, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_CLUSTER_PARENTCLUSTERID ON APOLLO_CONFIG."CLUSTER" (PARENTCLUSTERID);
CREATE INDEX IDX_CLUSTER_DATACHANGE_LASTTIME ON APOLLO_CONFIG."CLUSTER" (DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_CLUSTER_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG."CLUSTER"
  FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG."CLUSTER" IS '集群';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".NAME IS '集群名字';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".APPID IS 'App id';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".PARENTCLUSTERID IS '父cluster';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER"."COMMENT" IS '备注';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG."CLUSTER".DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建提交历史表
CREATE TABLE APOLLO_CONFIG.COMMIT (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CHANGESETS CLOB NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    NAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    "COMMENT" VARCHAR2(500),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.COMMIT ADD CONSTRAINT PK_APP_COMMIT PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_COMMIT_DATACHANGE_LASTTIME ON APOLLO_CONFIG.COMMIT (DATACHANGE_LASTTIME);
CREATE INDEX IDX_COMMIT_APPID ON APOLLO_CONFIG.COMMIT (APPID);
CREATE INDEX IDX_COMMIT_CLUSTERNAME ON APOLLO_CONFIG.COMMIT (CLUSTERNAME);
CREATE INDEX IDX_COMMIT_NAMESPACENAME ON APOLLO_CONFIG.COMMIT (NAMESPACENAME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_COMMIT_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.COMMIT
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.COMMIT IS 'commit 历史表';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.CHANGESETS IS '修改变更集';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT."COMMENT" IS '备注';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.COMMIT.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
--创建灰度规则表
CREATE TABLE APOLLO_CONFIG.GRAYRELEASERULE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    NAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    BRANCHNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    RULES CLOB DEFAULT '[]',
    RELEASEID NUMBER(11) DEFAULT 0 NOT NULL,
    BRANCHSTATUS NUMBER(2) DEFAULT 1,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.GRAYRELEASERULE ADD CONSTRAINT PK_GRAYRELEASERULE PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_GRAYRELEASERULE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.GRAYRELEASERULE (DATACHANGE_LASTTIME);
CREATE INDEX IDX_GRAYRELEASERULE_APP_CLUSTER_NAMESPACE ON APOLLO_CONFIG.GRAYRELEASERULE (APPID, CLUSTERNAME, NAMESPACENAME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_GRAYRELEASERULE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.GRAYRELEASERULE
  FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.GRAYRELEASERULE IS '灰度规则表';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.CLUSTERNAME IS 'Cluster Name';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.NAMESPACENAME IS 'Namespace Name';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.BRANCHNAME IS 'branch name';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.RULES IS '灰度规则';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.RELEASEID IS '灰度对应的release';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.BRANCHSTATUS IS '灰度分支状态: 0:删除分支,1:正在使用的规则 2：全量发布';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.GRAYRELEASERULE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建使用配置的应用实例表
CREATE TABLE APOLLO_CONFIG.INSTANCE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    DATACENTER VARCHAR2(64) DEFAULT 'default' NOT NULL,
    IP VARCHAR2(32) DEFAULT '' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.INSTANCE ADD CONSTRAINT PK_INSTANCE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.INSTANCE ADD CONSTRAINT UK_APP_CLUSTER_IP_DC UNIQUE (APPID, CLUSTERNAME, IP, DATACENTER);
-- 创建索引
CREATE INDEX IDX_INSTANCE_IP ON APOLLO_CONFIG.INSTANCE (IP);
CREATE INDEX IDX_INSTANCE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.INSTANCE (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_INSTANCE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.INSTANCE
  FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.INSTANCE IS '使用配置的应用实例';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.DATACENTER IS 'Data Center Name';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.IP IS 'instance ip';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建应用实例的配置信息
CREATE TABLE APOLLO_CONFIG.INSTANCECONFIG (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    INSTANCEID          NUMBER(11),
    CONFIGAPPID         VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CONFIGCLUSTERNAME   VARCHAR2(32) DEFAULT 'default' NOT NULL,
    CONFIGNAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    RELEASEKEY          VARCHAR2(64) DEFAULT '' NOT NULL,
    RELEASEDELIVERYTIME TIMESTAMP,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键约束
ALTER TABLE APOLLO_CONFIG.INSTANCECONFIG ADD CONSTRAINT PK_InstanceConfig PRIMARY KEY (ID);
-- 创建唯一索引 IX_UNIQUE_KEY
CREATE UNIQUE INDEX IX_UNIQUE_KEY ON APOLLO_CONFIG.INSTANCECONFIG (INSTANCEID,CONFIGAPPID,CONFIGNAMESPACENAME);
-- 创建普通索引 IX_ReleaseKey
CREATE INDEX IDX_INSTANCECONFIG_RELEASEKEY ON APOLLO_CONFIG.INSTANCECONFIG (RELEASEKEY);
CREATE INDEX IDX_INSTANCECONFIG_DATACHANGE_LASTTIME ON APOLLO_CONFIG.INSTANCECONFIG (DATACHANGE_LASTTIME);
CREATE INDEX IDX_INSTANCECONFIG_VALID_NAMESPACE ON APOLLO_CONFIG.INSTANCECONFIG (CONFIGAPPID,CONFIGCLUSTERNAME,CONFIGNAMESPACENAME,DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_INSTANCECONFIG_UPDATE_TIMESTAMP
    BEFORE UPDATE ON APOLLO_CONFIG.INSTANCECONFIG
    FOR EACH ROW
BEGIN
    :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 表注释
COMMENT ON TABLE APOLLO_CONFIG.INSTANCECONFIG IS '应用实例的配置信息';
-- 添加字段注释
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.Id IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.InstanceId IS 'Instance Id';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.ConfigAppId IS 'Config App Id';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.ConfigClusterName IS 'Config Cluster Name';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.ConfigNamespaceName IS 'Config Namespace Name';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.ReleaseKey IS '发布的Key';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.ReleaseDeliveryTime IS '配置获取时间';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.DataChange_CreatedTime IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.INSTANCECONFIG.DataChange_LastTime IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_CONFIG.ITEM (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAMESPACEID NUMBER(10) DEFAULT 0 NOT NULL,
    KEY VARCHAR2(128) DEFAULT 'default' NOT NULL,
    TYPE NUMBER(3) DEFAULT 0 NOT NULL,
    VALUE CLOB NOT NULL,
    "COMMENT" VARCHAR2(1024) DEFAULT '',
    LINENUM NUMBER(10) DEFAULT 0,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.ITEM ADD CONSTRAINT PK_CONFIG_ITEM PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_ITEM_NAMESPACEID ON APOLLO_CONFIG.ITEM (NAMESPACEID);
CREATE INDEX IDX_ITEM_DATACHANGE_LASTTIME ON APOLLO_CONFIG.ITEM (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_ITEM_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.ITEM
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.ITEM IS '配置项目';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.NAMESPACEID IS '集群NamespaceId';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.KEY IS '配置项Key';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.TYPE IS '配置项类型，0: String，1: Number，2: Boolean，3: JSON';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.VALUE IS '配置项值';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.LINENUM IS '行号';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.ITEM.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建命名空间表
CREATE TABLE APOLLO_CONFIG.NAMESPACE (
   ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
   APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
   CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
   NAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
   ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
   DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
   DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
   DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
   DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.NAMESPACE ADD CONSTRAINT PK_NAMESPACE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.NAMESPACE ADD CONSTRAINT UK_APP_CLUSTER_NS_DEL UNIQUE (APPID, CLUSTERNAME, NAMESPACENAME, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_NAMESPACE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.NAMESPACE (DATACHANGE_LASTTIME);
CREATE INDEX IDX_NAMESPACE_NAMESPACENAME ON APOLLO_CONFIG.NAMESPACE (NAMESPACENAME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_NAMESPACE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.NAMESPACE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.NAMESPACE IS '命名空间';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.CLUSTERNAME IS 'Cluster Name';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.NAMESPACENAME IS 'Namespace Name';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建namespace的编辑锁表
CREATE TABLE APOLLO_CONFIG.NAMESPACELOCK (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NAMESPACEID NUMBER(10) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.NAMESPACELOCK ADD CONSTRAINT PK_NAMESPACELOCK PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.NAMESPACELOCK ADD CONSTRAINT UK_NSID_DELETEDAT UNIQUE (NAMESPACEID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_NAMESPACELOCK_DATACHANGE_LASTTIME ON APOLLO_CONFIG.NAMESPACELOCK (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_NAMESPACELOCK_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.NAMESPACELOCK
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.NAMESPACELOCK IS 'namespace的编辑锁';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.ID IS '自增id';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.NAMESPACEID IS '集群NamespaceId';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.DATACHANGE_LASTTIME IS '最后修改时间';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.ISDELETED IS '软删除';
COMMENT ON COLUMN APOLLO_CONFIG.NAMESPACELOCK.DELETEDAT IS 'Delete timestamp based on milliseconds';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建发布表
CREATE TABLE APOLLO_CONFIG.RELEASE (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    RELEASEKEY VARCHAR2(64) DEFAULT '' NOT NULL,
    NAME VARCHAR2(64) DEFAULT 'default' NOT NULL,
    "COMMENT" VARCHAR2(256),
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    NAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    CONFIGURATIONS CLOB NOT NULL,
    ISABANDONED NUMBER(1) DEFAULT 0 NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.RELEASE ADD CONSTRAINT PK_RELEASE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.RELEASE ADD CONSTRAINT UK_RELEASEKEY_DEL_AT UNIQUE (RELEASEKEY, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_RELEASE_APP_CLUSTER_NS ON APOLLO_CONFIG.RELEASE (APPID, CLUSTERNAME, NAMESPACENAME);
CREATE INDEX IDX_RELEASE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.RELEASE (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_RELEASE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.RELEASE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.RELEASE IS '发布';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.RELEASEKEY IS '发布的Key';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.NAME IS '发布名字';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE."COMMENT" IS '发布说明';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.CONFIGURATIONS IS '发布配置';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.ISABANDONED IS '是否废弃';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_CONFIG.RELEASEHISTORY (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    CLUSTERNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    NAMESPACENAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    BRANCHNAME VARCHAR2(32) DEFAULT 'default' NOT NULL,
    RELEASEID NUMBER(11) DEFAULT 0 NOT NULL,
    PREVIOUSRELEASEID NUMBER(11) DEFAULT 0 NOT NULL,
    OPERATION NUMBER(3) DEFAULT 0 NOT NULL,
    OPERATIONCONTEXT CLOB NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.RELEASEHISTORY ADD CONSTRAINT PK_RELEASEHISTORY PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_RELEASEHISTORY_APP_CLUSTER_NS_BR ON APOLLO_CONFIG.RELEASEHISTORY (APPID, CLUSTERNAME, NAMESPACENAME, BRANCHNAME);
CREATE INDEX IDX_RELEASEHISTORY_RELEASEID ON APOLLO_CONFIG.RELEASEHISTORY (RELEASEID);
CREATE INDEX IDX_RELEASEHISTORY_DATACHANGE_LASTTIME ON APOLLO_CONFIG.RELEASEHISTORY (DATACHANGE_LASTTIME);
CREATE INDEX IDX_RELEASEHISTORY_PREVRELEASEID ON APOLLO_CONFIG.RELEASEHISTORY (PREVIOUSRELEASEID);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_RELEASEHISTORY_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.RELEASEHISTORY
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.RELEASEHISTORY IS '发布历史';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.CLUSTERNAME IS 'ClusterName';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.NAMESPACENAME IS 'namespaceName';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.BRANCHNAME IS '发布分支名';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.RELEASEID IS '关联的Release Id';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.PREVIOUSRELEASEID IS '前一次发布的ReleaseId';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.OPERATION IS '发布类型，0: 普通发布，1: 回滚，2: 灰度发布，3: 灰度规则更新，4: 灰度合并回主分支发布，5: 主分支发布灰度自动发布，6: 主分支回滚灰度自动发布，7: 放弃灰度';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.OPERATIONCONTEXT IS '发布上下文信息';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEHISTORY.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建发布消息表
CREATE TABLE APOLLO_CONFIG.RELEASEMESSAGE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    MESSAGE VARCHAR2(1024) DEFAULT '' NOT NULL,
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.RELEASEMESSAGE ADD CONSTRAINT PK_RELEASEMESSAGE PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_RELEASEMESSAGE_DATACHANGE_LASTTIME ON APOLLO_CONFIG.RELEASEMESSAGE (DATACHANGE_LASTTIME);
CREATE INDEX IDX_RELEASEMESSAGE_MESSAGE_PREFIX ON APOLLO_CONFIG.RELEASEMESSAGE (SUBSTR(MESSAGE, 1, 191));
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_RELEASEMESSAGE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.RELEASEMESSAGE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.RELEASEMESSAGE IS '发布消息';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEMESSAGE.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEMESSAGE.MESSAGE IS '发布的消息内容';
COMMENT ON COLUMN APOLLO_CONFIG.RELEASEMESSAGE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建配置服务自身配置表
CREATE TABLE APOLLO_CONFIG.SERVERCONFIG (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "KEY" VARCHAR2(64) DEFAULT 'default' NOT NULL,
    "CLUSTER" VARCHAR2(32) DEFAULT 'default' NOT NULL,
    "VALUE" VARCHAR2(2048) DEFAULT 'default' NOT NULL,
    "COMMENT" VARCHAR2(1024) DEFAULT '',
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.SERVERCONFIG ADD CONSTRAINT PK_SERVERCONFIG PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.SERVERCONFIG ADD CONSTRAINT UK_KEY_CLUSTER_DEL UNIQUE ("KEY", "CLUSTER", DELETEDAT);
-- 创建索引
CREATE INDEX IDX_SERVERCONFIG_DATACHANGE_LASTTIME ON APOLLO_CONFIG.SERVERCONFIG (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_SERVERCONFIG_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.SERVERCONFIG
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.SERVERCONFIG IS '配置服务自身配置';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG."KEY" IS '配置项Key';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG."CLUSTER" IS '配置对应的集群，default为不针对特定的集群';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG."VALUE" IS '配置项值';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.SERVERCONFIG.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建访问密钥表
CREATE TABLE APOLLO_CONFIG.ACCESSKEY (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    SECRET VARCHAR2(128) DEFAULT '' NOT NULL,
    "MODE" NUMBER(3) DEFAULT 0 NOT NULL,
    ISENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.ACCESSKEY ADD CONSTRAINT PK_ACCESSKEY PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.ACCESSKEY ADD CONSTRAINT UK_APP_SECRET_DEL UNIQUE (APPID, SECRET, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_ACCESSKEY_DATACHANGE_LASTTIME ON APOLLO_CONFIG.ACCESSKEY (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_ACCESSKEY_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.ACCESSKEY
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.ACCESSKEY IS '访问密钥';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.SECRET IS 'Secret';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY."MODE" IS '密钥模式，0: filter，1: observer';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.ISENABLED IS '1: enabled, 0: disabled';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.ACCESSKEY.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建注册中心表
CREATE TABLE APOLLO_CONFIG.SERVICEREGISTRY (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    SERVICENAME VARCHAR2(64) NOT NULL,
    URI VARCHAR2(64) NOT NULL,
    "CLUSTER" VARCHAR2(64) NOT NULL,
    METADATA VARCHAR2(1024) DEFAULT '{}' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_CONFIG.SERVICEREGISTRY ADD CONSTRAINT PK_SERVICEREGISTRY PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_CONFIG.SERVICEREGISTRY ADD CONSTRAINT UK_SERVICE_URI UNIQUE (SERVICENAME, URI);
-- 创建索引
CREATE INDEX IDX_SERVICEREGISTRY_DATACHANGE_LASTTIME ON APOLLO_CONFIG.SERVICEREGISTRY (DATACHANGE_LASTTIME);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_SERVICEREGISTRY_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.SERVICEREGISTRY
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.SERVICEREGISTRY IS '注册中心';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.SERVICENAME IS '服务名';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.URI IS '服务地址';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY."CLUSTER" IS '集群，可以用来标识apollo.cluster或者网络分区';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.METADATA IS '元数据，key value结构的json object，为了方面后面扩展功能而不需要修改表结构';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.SERVICEREGISTRY.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建审计日志表
CREATE TABLE APOLLO_CONFIG.AUDITLOG (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TRACEID VARCHAR2(32) DEFAULT '' NOT NULL,
    SPANID VARCHAR2(32) DEFAULT '' NOT NULL,
    PARENTSPANID VARCHAR2(32),
    FOLLOWSFROMSPANID VARCHAR2(32),
    OPERATOR VARCHAR2(64) DEFAULT 'anonymous' NOT NULL,
    OPTYPE VARCHAR2(50) DEFAULT 'default' NOT NULL,
    OPNAME VARCHAR2(150) DEFAULT 'default' NOT NULL,
    DESCRIPTION VARCHAR2(200),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64),
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IDX_AUDITLOG_TRACEID ON APOLLO_CONFIG.AUDITLOG (TRACEID);
CREATE INDEX IDX_AUDITLOG_OPNAME ON APOLLO_CONFIG.AUDITLOG (OPNAME);
CREATE INDEX IDX_AUDITLOG_DATACHANGE_CREATEDTIME ON APOLLO_CONFIG.AUDITLOG (DATACHANGE_CREATEDTIME);
CREATE INDEX IDX_AUDITLOG_OPERATOR ON APOLLO_CONFIG.AUDITLOG (OPERATOR);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_AUDITLOG_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.AUDITLOG
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.AUDITLOG IS '审计日志表';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.TRACEID IS '链路全局唯一ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.SPANID IS '跨度ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.PARENTSPANID IS '父跨度ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.FOLLOWSFROMSPANID IS '上一个兄弟跨度ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.OPERATOR IS '操作人';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.OPTYPE IS '操作类型';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.OPNAME IS '操作名称';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DESCRIPTION IS '备注';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOG.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
-- 创建审计日志数据变动表
CREATE TABLE APOLLO_CONFIG.AUDITLOGDATAINFLUENCE (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SPANID CHAR(32) DEFAULT '' NOT NULL,
    INFLUENCEENTITYID VARCHAR2(50) DEFAULT '0' NOT NULL,
    INFLUENCEENTITYNAME VARCHAR2(50) DEFAULT 'default' NOT NULL,
    FIELDNAME VARCHAR2(50),
    FIELDOLDVALUE VARCHAR2(500),
    FIELDNEWVALUE VARCHAR2(500),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64),
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace APOLLO_CONFIG_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IDX_AUDITLOGDATAINFLUENCE_SPANID ON APOLLO_CONFIG.AUDITLOGDATAINFLUENCE (SPANID);
CREATE INDEX IDX_AUDITLOGDATAINFLUENCE_DATACHANGE_CREATEDTIME ON APOLLO_CONFIG.AUDITLOGDATAINFLUENCE (DATACHANGE_CREATEDTIME);
CREATE INDEX IDX_AUDITLOGDATAINFLUENCE_ENTITYID ON APOLLO_CONFIG.AUDITLOGDATAINFLUENCE (INFLUENCEENTITYID);
-- 创建自动更新时间戳的触发器
CREATE OR REPLACE TRIGGER APOLLO_CONFIG_AUDITLOGDATAINFLUENCE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_CONFIG.AUDITLOGDATAINFLUENCE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_CONFIG.AUDITLOGDATAINFLUENCE IS '审计日志数据变动表';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.ID IS '主键';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.SPANID IS '跨度ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.INFLUENCEENTITYID IS '记录ID';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.INFLUENCEENTITYNAME IS '表名';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.FIELDNAME IS '字段名称';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.FIELDOLDVALUE IS '字段旧值';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.FIELDNEWVALUE IS '字段新值';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_CONFIG.AUDITLOGDATAINFLUENCE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
--初始化配置
INSERT INTO APOLLO_CONFIG.SERVERCONFIG ("KEY", "CLUSTER", "VALUE", "COMMENT") VALUES ('eureka.service.url', 'default', 'http://localhost:8080/eureka/', 'Eureka服务Url，多个service以英文逗号分隔');
INSERT INTO APOLLO_CONFIG.SERVERCONFIG ("KEY", "CLUSTER", "VALUE", "COMMENT") VALUES ('namespace.lock.switch', 'default', 'false', '一次发布只能有一个人修改开关');
INSERT INTO APOLLO_CONFIG.SERVERCONFIG ("KEY", "CLUSTER", "VALUE", "COMMENT") VALUES ('item.key.length.limit', 'default', '128', 'item key 最大长度限制');
INSERT INTO APOLLO_CONFIG.SERVERCONFIG ("KEY", "CLUSTER", "VALUE", "COMMENT") VALUES ('item.value.length.limit', 'default', '20000', 'item value最大长度限制');
INSERT INTO APOLLO_CONFIG.SERVERCONFIG ("KEY", "CLUSTER", "VALUE", "COMMENT") VALUES ('config-service.cache.enabled', 'default', 'false', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗');
COMMIT;
