-- 删除用户及TABLESPACE
-- ALTER TABLESPACE APOLLO_PORTAL_TABLESPACE OFFLINE;
-- DROP USER APOLLO_PORTAL CASCADE;
-- DROP TABLESPACE APOLLO_PORTAL_TABLESPACE INCLUDING CONTENTS AND DATAFILES;
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建TABLESPACE以及对应的dbf文件初始大小
CREATE TABLESPACE APOLLO_PORTAL_TABLESPACE DATAFILE '/opt/oracle/oradata/ORCL/ORCLPDB/APOLLO_PORTAL_TABLESPACE.dbf' SIZE 5G AUTOEXTEND OFF;
CREATE USER APOLLO_PORTAL IDENTIFIED BY 123456 DEFAULT TABLESPACE APOLLO_PORTAL_TABLESPACE;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO APOLLO_PORTAL;
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- APP 表定义
CREATE TABLE APOLLO_PORTAL.APP (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    NAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ORGID VARCHAR2(32) DEFAULT 'default' NOT NULL,
    ORGNAME VARCHAR2(64) DEFAULT 'default' NOT NULL,
    OWNERNAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    OWNEREMAIL VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 唯一约束和索引
ALTER TABLE APOLLO_PORTAL.APP ADD CONSTRAINT UK_P_APPID_DELETEDAT UNIQUE (APPID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_P_APP_NAME ON APOLLO_PORTAL.APP (SUBSTR(NAME, 1, 191));
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_APP_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.APP
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.APP IS '应用表';
COMMENT ON COLUMN APOLLO_PORTAL.APP.ID IS '主键';
COMMENT ON COLUMN APOLLO_PORTAL.APP.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_PORTAL.APP.NAME IS '应用名称';
COMMENT ON COLUMN APOLLO_PORTAL.APP.ORGID IS '组织ID';
COMMENT ON COLUMN APOLLO_PORTAL.APP.ORGNAME IS '组织名称';
COMMENT ON COLUMN APOLLO_PORTAL.APP.OWNERNAME IS '负责人名称';
COMMENT ON COLUMN APOLLO_PORTAL.APP.OWNEREMAIL IS '负责人邮箱';
COMMENT ON COLUMN APOLLO_PORTAL.APP.ISDELETED IS '是否删除';
COMMENT ON COLUMN APOLLO_PORTAL.APP.DELETEDAT IS '删除时间戳';
COMMENT ON COLUMN APOLLO_PORTAL.APP.DATACHANGE_CREATEDBY IS '创建者';
COMMENT ON COLUMN APOLLO_PORTAL.APP.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.APP.DATACHANGE_LASTMODIFIEDBY IS '最后修改者';
COMMENT ON COLUMN APOLLO_PORTAL.APP.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.APPNAMESPACE (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NAME VARCHAR2(32) DEFAULT '' NOT NULL,
    APPID VARCHAR2(64) DEFAULT '' NOT NULL,
    FORMAT VARCHAR2(32) DEFAULT 'properties' NOT NULL,
    ISPUBLIC NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISPUBLIC IN (0,1)),
    "COMMENT" VARCHAR2(64) DEFAULT '' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.APPNAMESPACE ADD CONSTRAINT PK_P_APPNAMESPACE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.APPNAMESPACE  ADD CONSTRAINT UK_P_APPID_NAME_DEL UNIQUE (APPID, NAME, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_NAME_APPID ON APOLLO_PORTAL.APPNAMESPACE (NAME, APPID);
CREATE INDEX IDX_APPNAMESPACE_DATACHANGE_LASTTIME ON APOLLO_PORTAL.APPNAMESPACE (DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_APPNAMESPACE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.APPNAMESPACE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.APPNAMESPACE IS '应用namespace定义';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.ID IS '自增主键';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.NAME IS 'namespace名字，注意，需要全局唯一';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.APPID IS 'app id';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.FORMAT IS 'namespace的format类型';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.ISPUBLIC IS 'namespace是否为公共';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.APPNAMESPACE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.CONSUMER (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    NAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ORGID VARCHAR2(32) DEFAULT 'default' NOT NULL,
    ORGNAME VARCHAR2(64) DEFAULT 'default' NOT NULL,
    OWNERNAME VARCHAR2(500) DEFAULT 'default' NOT NULL,
    OWNEREMAIL VARCHAR2(500) DEFAULT 'default' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.CONSUMER ADD CONSTRAINT PK_P_CONSUMER PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.CONSUMER ADD CONSTRAINT UK_P_APPID_DEL_AT UNIQUE (APPID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_CONSUMER_DATACHANGE_LASTTIME ON APOLLO_PORTAL.CONSUMER (DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_CONSUMER_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.CONSUMER
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.CONSUMER IS '开放API消费者';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.NAME IS '应用名';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.ORGID IS '部门Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.ORGNAME IS '部门名字';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.OWNERNAME IS 'ownerName';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.OWNEREMAIL IS 'ownerEmail';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMER.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.CONSUMERAUDIT (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CONSUMERID NUMBER(11),
    URI VARCHAR2(1024) DEFAULT '' NOT NULL,
    METHOD VARCHAR2(16) DEFAULT '' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.CONSUMERAUDIT ADD CONSTRAINT PK_P_CONSUMERAUDIT PRIMARY KEY (ID);
-- 创建索引
CREATE INDEX IDX_CONSUMERAUDIT_DATACHANGE_LASTTIME ON APOLLO_PORTAL.CONSUMERAUDIT (DATACHANGE_LASTTIME);
CREATE INDEX IDX_CONSUMERID ON APOLLO_PORTAL.CONSUMERAUDIT (CONSUMERID);
CREATE INDEX IDX_METHOD_URI ON APOLLO_PORTAL.CONSUMERAUDIT (METHOD, SUBSTR(URI, 1, 128));
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_CONSUMERAUDIT_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.CONSUMERAUDIT
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.CONSUMERAUDIT IS 'consumer审计表';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.CONSUMERID IS 'Consumer Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.URI IS '访问的Uri';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.METHOD IS '访问的Method';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERAUDIT.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.CONSUMERROLE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CONSUMERID NUMBER(11),
    ROLEID NUMBER(10),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.CONSUMERROLE ADD CONSTRAINT PK_P_CONSUMERROLE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.CONSUMERROLE ADD CONSTRAINT UK_P_CONSUMER_ROLE_DEL UNIQUE (CONSUMERID, ROLEID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_CONSUMERROLE_DATACHANGE_LASTTIME ON APOLLO_PORTAL.CONSUMERROLE (DATACHANGE_LASTTIME);
CREATE INDEX IDX_ROLEID ON APOLLO_PORTAL.CONSUMERROLE (ROLEID);
CREATE INDEX IDX_CONSUMERID_DEL ON APOLLO_PORTAL.CONSUMERROLE (CONSUMERID, ISDELETED);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_CONSUMERROLE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.CONSUMERROLE
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.CONSUMERROLE IS 'consumer和role的绑定表';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.CONSUMERID IS 'Consumer Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.ROLEID IS 'Role Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERROLE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.CONSUMERTOKEN (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    CONSUMERID NUMBER(11),
    TOKEN VARCHAR2(128) DEFAULT '' NOT NULL,
    RATELIMIT NUMBER DEFAULT 0 NOT NULL,
    EXPIRES TIMESTAMP DEFAULT TIMESTAMP '2099-01-01 00:00:00' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;

-- 添加主键
ALTER TABLE APOLLO_PORTAL.CONSUMERTOKEN ADD CONSTRAINT PK_P_CONSUMERTOKEN PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.CONSUMERTOKEN ADD CONSTRAINT UK_P_TOKEN_DEL_AT UNIQUE (TOKEN, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_CONSUMERTOKEN_DATACHANGE_LASTTIME ON APOLLO_PORTAL.CONSUMERTOKEN (DATACHANGE_LASTTIME);
CREATE INDEX IDX_TOKEN_EXPIRES ON APOLLO_PORTAL.CONSUMERTOKEN (TOKEN, EXPIRES);
CREATE INDEX IDX_CONSUMERID_STATUS ON APOLLO_PORTAL.CONSUMERTOKEN (CONSUMERID, ISDELETED);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_CONSUMERTOKEN_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.CONSUMERTOKEN
    FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.CONSUMERTOKEN IS 'consumer token表';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.CONSUMERID IS 'ConsumerId';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.TOKEN IS 'token';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.RATELIMIT IS '限流值';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.EXPIRES IS 'token失效时间';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.CONSUMERTOKEN.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.FAVORITE (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 23 INCREMENT BY 1) NOT NULL,
    USERID VARCHAR2(32) DEFAULT 'default' NOT NULL,
    APPID VARCHAR2(64) DEFAULT 'default' NOT NULL,
    POSITION NUMBER(10) DEFAULT 10000 NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.FAVORITE ADD CONSTRAINT PK_P_FAVORITE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.FAVORITE ADD CONSTRAINT UK_P_USER_APP_DEL UNIQUE (USERID, APPID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_APPID ON APOLLO_PORTAL.FAVORITE (APPID);
CREATE INDEX IDX_FAVORITE_DATACHANGE_LASTTIME ON APOLLO_PORTAL.FAVORITE (DATACHANGE_LASTTIME);
CREATE INDEX IDX_USER_POSITION ON APOLLO_PORTAL.FAVORITE (USERID, POSITION);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_FAVORITE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.FAVORITE FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.FAVORITE IS '应用收藏表';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.ID IS '主键';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.USERID IS '收藏的用户';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.APPID IS 'AppID';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.POSITION IS '收藏顺序';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.FAVORITE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.PERMISSION (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    PERMISSIONTYPE VARCHAR2(32) DEFAULT '' NOT NULL,
    TARGETID VARCHAR2(256) DEFAULT '' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.PERMISSION ADD CONSTRAINT PK_P_PERMISSION PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.PERMISSION ADD CONSTRAINT UK_P_TARGET_PERM_TYPE_DEL UNIQUE (TARGETID, PERMISSIONTYPE, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_PERMISSION_DATACHANGE_LASTTIME ON APOLLO_PORTAL.PERMISSION (DATACHANGE_LASTTIME);
CREATE INDEX IDX_PERMISSION_TYPE ON APOLLO_PORTAL.PERMISSION (PERMISSIONTYPE);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_PERMISSION_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.PERMISSION FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.PERMISSION IS 'permission表';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.PERMISSIONTYPE IS '权限类型';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.TARGETID IS '权限对象类型';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.PERMISSION.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.ROLE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    ROLENAME VARCHAR2(256) DEFAULT '' NOT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.ROLE ADD CONSTRAINT PK_P_ROLE PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.ROLE ADD CONSTRAINT UK_P_ROLENAME_DEL_AT UNIQUE (ROLENAME, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_ROLE_DATACHANGE_LASTTIME ON APOLLO_PORTAL.ROLE (DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_ROLE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.ROLE FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.ROLE IS '角色表';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.ROLENAME IS 'Role name';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.ROLE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
-- 创建表
CREATE TABLE APOLLO_PORTAL.ROLEPERMISSION (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    ROLEID NUMBER(10),
    PERMISSIONID NUMBER(10),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 添加主键
ALTER TABLE APOLLO_PORTAL.ROLEPERMISSION ADD CONSTRAINT PK_P_ROLEPERMISSION PRIMARY KEY (ID);
-- 添加唯一约束
ALTER TABLE APOLLO_PORTAL.ROLEPERMISSION ADD CONSTRAINT UK_P_ROLE_PERM_DEL_AT UNIQUE (ROLEID, PERMISSIONID, DELETEDAT);
-- 创建索引
CREATE INDEX IDX_ROLEPERMISSION_DATACHANGE_LASTTIME ON APOLLO_PORTAL.ROLEPERMISSION (DATACHANGE_LASTTIME);
CREATE INDEX IDX_PERMISSIONID ON APOLLO_PORTAL.ROLEPERMISSION (PERMISSIONID);
CREATE INDEX IDX_ROLEID_STATUS ON APOLLO_PORTAL.ROLEPERMISSION (ROLEID, ISDELETED);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_ROLEPERMISSION_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.ROLEPERMISSION FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
-- 添加注释
COMMENT ON TABLE APOLLO_PORTAL.ROLEPERMISSION IS '角色和权限的绑定表';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.ROLEID IS 'Role Id';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.PERMISSIONID IS 'Permission Id';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.ROLEPERMISSION.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.SERVERCONFIG (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    KEY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    VALUE VARCHAR2(2048) DEFAULT 'default' NOT NULL,
    "COMMENT" VARCHAR2(1024),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_P_SERVERCONFIG PRIMARY KEY (ID),
    CONSTRAINT UK_P_KEY_DELETEDAT UNIQUE (KEY, DELETEDAT)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建普通索引（唯一约束已自动创建索引，可显式创建其他索引）
CREATE INDEX IDX_SERVERCONFIG_DATACHANGE_LASTTIME ON APOLLO_PORTAL.SERVERCONFIG(DATACHANGE_LASTTIME);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_SERVERCONFIG_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.SERVERCONFIG FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE APOLLO_PORTAL.SERVERCONFIG IS '配置服务自身配置';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.KEY IS '配置项Key';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.VALUE IS '配置项值';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG."COMMENT" IS '注释';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.SERVERCONFIG.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.USERROLE (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    USERID VARCHAR2(128) DEFAULT '' NOT NULL,
    ROLEID NUMBER(10) DEFAULT NULL,
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64) DEFAULT 'default' NOT NULL,
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_P_USERROLE PRIMARY KEY (ID),
    CONSTRAINT UK_P_USERID_ROLEID_DELETEDAT UNIQUE (USERID, ROLEID, DELETEDAT)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IX_DATACHANGE_LASTTIME ON APOLLO_PORTAL.USERROLE(DATACHANGE_LASTTIME);
CREATE INDEX IX_ROLEID ON APOLLO_PORTAL.USERROLE(ROLEID);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_USERROLE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.USERROLE FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE  APOLLO_PORTAL.USERROLE IS '用户和role的绑定表';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.ID IS '自增Id';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.USERID IS '用户身份标识';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.ROLEID IS 'Role Id';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN  APOLLO_PORTAL.USERROLE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.USERS (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    USERNAME VARCHAR2(64) DEFAULT 'default' NOT NULL,
    PASSWORD VARCHAR2(512) DEFAULT 'default' NOT NULL,
    USERDISPLAYNAME VARCHAR2(512) DEFAULT 'default' NOT NULL,
    EMAIL VARCHAR2(64) DEFAULT 'default' NOT NULL,
    ENABLED NUMBER(4) DEFAULT NULL,
    CONSTRAINT PK_P_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_P_USERS UNIQUE (USERNAME)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_USERS_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.USERS FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE APOLLO_PORTAL.USERS IS '用户表';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.USERNAME IS '用户登录账户';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.PASSWORD IS '密码';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.USERDISPLAYNAME IS '用户名称';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.EMAIL IS '邮箱地址';
COMMENT ON COLUMN APOLLO_PORTAL.USERS.ENABLED IS '是否有效';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.AUTHORITIES (
    ID NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    USERNAME VARCHAR2(64) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_P_AUTHORITIES PRIMARY KEY (ID)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
COMMENT ON TABLE APOLLO_PORTAL.AUTHORITIES IS '用户权限表';
COMMENT ON COLUMN APOLLO_PORTAL.AUTHORITIES.ID IS '自增Id';
COMMENT ON COLUMN APOLLO_PORTAL.AUTHORITIES.USERNAME IS '用户名';
COMMENT ON COLUMN APOLLO_PORTAL.AUTHORITIES.AUTHORITY IS '权限名称';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME NUMBER(19) NOT NULL,
    LAST_ACCESS_TIME NUMBER(19) NOT NULL,
    MAX_INACTIVE_INTERVAL NUMBER(10) NOT NULL,
    EXPIRY_TIME NUMBER(19) NOT NULL,
    PRINCIPAL_NAME VARCHAR2(100),
    CONSTRAINT PK_P_SPRING_SESSION PRIMARY KEY (PRIMARY_ID)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE UNIQUE INDEX IX_SESSION_ID ON SPRING_SESSION(SESSION_ID);
CREATE INDEX IX_EXPIRY_TIME ON SPRING_SESSION(EXPIRY_TIME);
CREATE INDEX IX_PRINCIPAL_NAME ON SPRING_SESSION(PRINCIPAL_NAME);
COMMENT ON TABLE APOLLO_PORTAL.SPRING_SESSION IS 'Spring 会话存储表';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.PRIMARY_ID IS '主会话ID';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.SESSION_ID IS '会话ID';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.CREATION_TIME IS '创建时间（毫秒）';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.LAST_ACCESS_TIME IS '最后访问时间（毫秒）';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.MAX_INACTIVE_INTERVAL IS '最大非活动间隔（秒）';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.EXPIRY_TIME IS '过期时间（毫秒）';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION.PRINCIPAL_NAME IS '用户名称';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT PK_P_SPRING_SESSION_ATTRIBUTES PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT FK_SPRING_SESSION_ATTRIBUTES_SESSION FOREIGN KEY (SESSION_PRIMARY_ID)
    REFERENCES SPRING_SESSION(PRIMARY_ID)
    ON DELETE CASCADE
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
COMMENT ON TABLE APOLLO_PORTAL.SPRING_SESSION_ATTRIBUTES IS 'Spring 会话属性存储表';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID IS '关联的主会话ID';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME IS '会话属性名称';
COMMENT ON COLUMN APOLLO_PORTAL.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES IS '属性值（二进制）';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.AUDITLOG (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    TRACEID VARCHAR2(32) DEFAULT '' NOT NULL,
    SPANID VARCHAR2(32) DEFAULT '' NOT NULL,
    PARENTSPANID VARCHAR2(32),
    FOLLOWSFROMSPANID VARCHAR2(32),
    OPERATOR VARCHAR2(64) DEFAULT 'anonymous' NOT NULL,
    OPTYPE VARCHAR2(50) DEFAULT 'default' NOT NULL,
    OPNAME VARCHAR2(150) DEFAULT 'default' NOT NULL,
    DESCRIPTION VARCHAR2(200),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64),
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_P_AUDITLOG PRIMARY KEY (ID)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IX_TRACEID ON APOLLO_PORTAL.AUDITLOG(TRACEID);
CREATE INDEX IX_OPNAME ON APOLLO_PORTAL.AUDITLOG(OPNAME);
CREATE INDEX IX_DATACHANGE_CREATEDTIME ON APOLLO_PORTAL.AUDITLOG(DATACHANGE_CREATEDTIME);
CREATE INDEX IX_OPERATOR ON APOLLO_PORTAL.AUDITLOG(OPERATOR);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_AUDITLOG_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.AUDITLOG FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE APOLLO_PORTAL.AUDITLOG IS '审计日志表';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.ID IS '主键';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.TRACEID IS '链路全局唯一ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.SPANID IS '跨度ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.PARENTSPANID IS '父跨度ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.FOLLOWSFROMSPANID IS '上一个兄弟跨度ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.OPERATOR IS '操作人';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.OPTYPE IS '操作类型';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.OPNAME IS '操作名称';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DESCRIPTION IS '备注';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOG.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
CREATE TABLE APOLLO_PORTAL.AUDITLOGDATAINFLUENCE (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    SPANID CHAR(32) DEFAULT '' NOT NULL,
    INFLUENCEENTITYID VARCHAR2(50) DEFAULT '0' NOT NULL,
    INFLUENCEENTITYNAME VARCHAR2(50) DEFAULT 'default' NOT NULL,
    FIELDNAME VARCHAR2(50),
    FIELDOLDVALUE VARCHAR2(500),
    FIELDNEWVALUE VARCHAR2(500),
    ISDELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDELETED IN (0,1)),
    DELETEDAT NUMBER(20) DEFAULT 0 NOT NULL,
    DATACHANGE_CREATEDBY VARCHAR2(64),
    DATACHANGE_CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATACHANGE_LASTMODIFIEDBY VARCHAR2(64) DEFAULT '',
    DATACHANGE_LASTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_P_AUDITLOGDATAINFLUENCE PRIMARY KEY (ID)
) tablespace APOLLO_PORTAL_TABLESPACE
  pctfree 10
  initrans 1
  maxtrans 255;
-- 创建索引
CREATE INDEX IX_SPANID ON APOLLO_PORTAL.AUDITLOGDATAINFLUENCE(SPANID);
CREATE INDEX IX_AUDITLOGDATAINFLUENCE_DATACHANGE_CREATEDTIME ON APOLLO_PORTAL.AUDITLOGDATAINFLUENCE(DATACHANGE_CREATEDTIME);
CREATE INDEX IX_INFLUENCEENTITYID ON APOLLO_PORTAL.AUDITLOGDATAINFLUENCE(INFLUENCEENTITYID);
-- 创建触发器
CREATE OR REPLACE TRIGGER APOLLO_PORTAL_AUDITLOGDATAINFLUENCE_UPDATE_TIMESTAMP
BEFORE UPDATE ON APOLLO_PORTAL.AUDITLOGDATAINFLUENCE FOR EACH ROW
BEGIN
  :new.DATACHANGE_LASTTIME := CURRENT_TIMESTAMP;
END;
/
COMMENT ON TABLE APOLLO_PORTAL.AUDITLOGDATAINFLUENCE IS '审计日志数据变动表';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.ID IS '主键';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.SPANID IS '跨度ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.INFLUENCEENTITYID IS '记录ID';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.INFLUENCEENTITYNAME IS '表名';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.FIELDNAME IS '字段名称';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.FIELDOLDVALUE IS '字段旧值';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.FIELDNEWVALUE IS '字段新值';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.ISDELETED IS '1: deleted, 0: normal';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.DELETEDAT IS 'Delete timestamp based on milliseconds';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.DATACHANGE_CREATEDBY IS '创建人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.DATACHANGE_CREATEDTIME IS '创建时间';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.DATACHANGE_LASTMODIFIEDBY IS '最后修改人邮箱前缀';
COMMENT ON COLUMN APOLLO_PORTAL.AUDITLOGDATAINFLUENCE.DATACHANGE_LASTTIME IS '最后修改时间';
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('apollo.portal.envs', 'dev', '可支持的环境列表');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('organizations', '[{"orgId":"TEST1","orgName":"样例部门1"},{"orgId":"TEST2","orgName":"样例部门2"}]', '部门列表');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('superAdmin', 'apollo', 'Portal超级管理员');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('api.readTimeout', '10000', 'http接口read timeout');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('consumer.token.salt', 'someSalt', 'consumer token salt');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('admin.createPrivateNamespace.switch', 'true', '是否允许项目管理员创建私有namespace');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('configView.memberOnly.envs', 'pro', '只对项目成员显示配置信息的环境列表，多个env以英文逗号分隔');
INSERT INTO APOLLO_PORTAL.SERVERCONFIG (KEY, VALUE, "COMMENT") VALUES ('apollo.portal.meta.servers', '{}', '各环境Meta Service列表');

INSERT INTO APOLLO_PORTAL.USERS (USERNAME, PASSWORD, USERDISPLAYNAME, EMAIL, ENABLED) VALUES ('apollo', '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS', 'apollo', 'apollo@acme.com', 1);

INSERT INTO APOLLO_PORTAL.AUTHORITIES (USERNAME, AUTHORITY) VALUES ('apollo', 'ROLE_user');
COMMIT;

